### ISSUE TITLE
커뮤니티

### ISSUE THREAD

**Issue by wddoods015** [AICC-PFLOW/webDev#12]

**Comment by wddoods015** [comment]
커뮤니티 리스트를 보여줄 페이지와 해당 리스트를 클릭하면 보여질 상세 페이지 폼은 구성을 완료했습니다. DB랑 API준비되면 알려주시면 로직 구현 하려고 합니다.

**Comment by witchking20** [comment]
@wddoods015 

게시판 불러오는쪽은 API완료했습니다.
/api/noticeboard

최근 게시글 3개 보내주도록했습니다.
post_id
title
content
category
user_id
written_datetime
update_datetime

**Comment by wddoods015** [comment]
user 로그인 할때 id or email 변경요청

**Comment by witchking20** [comment]
@wddoods015

게시판 상세 불러오는쪽 API완료했습니다.
/api/board/:boardid

반환값은 아직 DB미완성이라 기존 게시판 불러올때 데이터와 같습니다.

**Comment by witchking20** [comment]
게시판

CRUD 완료  
test진행중

**Comment by wddoods015** [comment]
커뮤니티 카테고리 구상

ex-
https://www.example.com/community?category=취준일상

클라이언트에서 클릭이벤트 발생할 때,  쿼리스트링으로 해당 카테고리 이름이 쿼리스트링으로 url에 추가되도록 설정.
서버에서는 쿼리스트링을 이용해 카테고리를 필터링해서 데이터 반환처리를 해주시면 될 것 같습니다.

**Comment by witchking20** [comment]
댓글 restapi CRUD 완료
test진행중

**Comment by Worldofgentleken** [comment]
시작날짜 끝나는 날짜 입력해주세요

**Comment by wddoods015** [comment]
09/13
커뮤니티 전체 포스트 리스트 불러오는 것 확인했습니다.

카테고리 파라미터로 동적 라우팅 처리, 프론트에서 필터링 확인 대기하고 있습니다.

**Comment by wddoods015** [comment]
09/20

카테고리 태그 클릭 초기화 이슈 해결

**Comment by Bong-jun-jang** [comment]
09/20

- 커뮤니티 관련 모든 api 구현 완료
-> 전체출력, 카테고리에 따라 분류하여 출력, 상세 페이지 출력, 글쓰기, 댓글 쓰기

- 테스트 진행하며 예외처리 추가 예정
