### ISSUE TITLE
로그인 & 회원가입

### ISSUE THREAD

**Issue by wddoods015** [AICC-PFLOW/webDev#13]
24/09/13 기능 구현 완료

**Comment by wddoods015** [comment]
24/08/15 ~ 24/08/19

로그인 & 회원가입 - 봉준, 호준
2차 프로젝트 발표 후 FeedBack 수정 및 보수 - 재영

반응형 CSS
저장시 알림 이벤트 추가
이미지 용량제한 alert 추가
경력 여러개 저장하기
주소 input 시/군/구, 상세주소로 두개로 나눠서 받기
기술태그를 기본정보 스텝에서 받기
next버튼클릭시 저장, 다음 스텝으로 라우팅 / 사이드바 로직 수정
24/08/19~

이력서 문구추천 api 가져오기
챗봇 프론트
게시판

**Comment by wddoods015** [comment]
24-08-28

호준님 수정한 회원가입 리액트 파일 합치기 완료.

**Comment by Worldofgentleken** [comment]
시작 끝나는 날짜 입력 해주세여~

**Comment by wddoods015** [comment]
2024/09/09 - 2024/09/11(예상종료시점) 

회원가입 시점에서 이력서 작성에 필요한 유저 개인정보 받기 수정.

로그인 & 회원가입 테스트 완료.

**Comment by wddoods015** [comment]
회원가입
로그인 기능 구현 & 테스트 완료입니다.
