### ISSUE TITLE
백엔드 진행상황

### ISSUE THREAD

**Issue by witchking20** [AICC-PFLOW/webDev#9]
개발: node 회사 검색 시스템 코딩시작
입력 받은 키값 기준으로 DB에서 필터링

**Comment by witchking20** [comment]
### DB 설계
1. 요구사항 분석 (페르소나 7명, 회사검색, 회사추천, 이력서저장, 자소서,  ) : 완료
2. 개념적 설계(ERD 작성) : 진행중
3. 논리적 설계(정규화)
4. 물리적 설계
5. 구현 및 테스트
6. 튜닝 및 최적화

### 검색 기능 구현
node를 사용해 클라이언트가 원하는 버튼(값)을 클릭 했을때 그 버튼에 맞는 데이터를 DB서버에서 필터링 한 후 출력 구현 : 진행중

**Comment by Bong-jun-jang** [comment]
~ 8/9
입력 받은 키값 기준(button id)으로 DB에서 필터링 작업 완료
8/11 ~ 
react + node.js + DB 연동 진행 예정

**Comment by witchking20** [comment]
DB 설계
요구사항 분석 (페르소나 7명, 회사검색, 회사추천, 이력서저장, 자소서, ) : 완료
개념적 설계(ERD 작성) : 이력서 테이블 설계완료, 채용공고 데이터 설계중
논리적 설계(정규화)
물리적 설계
구현 및 테스트
튜닝 및 최적화

검색 기능 구현
검색 기능 HTML로 구현 완료후 react로 변환 완료 코드 리뷰 진행중

2차 프로젝트 직후 크롤링, 자연어처리, 게시판 팀으로 나뉘어 진행예정

**Comment by Bong-jun-jang** [comment]
8/13 ~ 
이상현, 장봉준
원티드 채용공고 직군별로 나누어서 전체 데이터 크롤링 작업 시작

진행상황에 따라 내용 공유드리겠습니다.

**Comment by witchking20** [comment]
8/14 ~
장봉준, 김호준

1. 테이블에 저장 되어있는 7개의 페르소나로 로그인 및 이력서 작성 페이지 연동 (구현중)

**Comment by Bong-jun-jang** [comment]
8/22 

로그인, 회원가입, 회원탈퇴 기능 구현 완료
프론트 담당 재영님과 소통하며 기능 추가, 보완 할 예정

**Comment by witchking20** [comment]
8월26일 ~ 9월1일
장봉준,김호준

1. 로그인&회원가입 다듬기 + DB
2. 이력서 페이지 BE작업 + DB
3. 게시판 FE/BE

**Comment by pythonize** [comment]
8/26 API 명세서, DB설계 초안 작업 완료
8/26~8/30 BE FE 간 회의 후 수정/보완 계획

**Comment by Worldofgentleken** [comment]
@witchking20 @Bong-jun-jang @pythonize 
해당 이휴 완료로 돌리니다.
각 작업 단위로 이슈 새로 생성해서 올려주세요.
